version: '3.7'
services:

  services-php:
    container_name: services-php-fpm
    build: ./docker/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/:cached
    networks:
      - php

  services-nginx:
    container_name: nginx
    build: docker/nginx
    ports:
      - "81:81"
    depends_on:
      - services-php
    networks:
      - php
    volumes:
      - ./:/var/www/:cached
      - ./docker/logs/nginx-back:/var/log/nginx:cached

networks:
  php:
